### ISSUE TITLE
After using MakeReadable for a few minutes, the memory keeps rising and overflowing

### ISSUE THREAD

**Issue by freefer** [needle-mirror/com.unity.sentis#1]
I use a web camera to capture each frame of the image and perform inference in the update function
After using MakeReadable for a few minutes, the memory keeps rising and overflowing
 
using TensorFloat tensor = TextureConverter.ToTensor(texture, OnnxModel.Input.Width, OnnxModel.Input.Height, OnnxModel.Input.Channels);

 var m_Inputs = new Dictionary<string, Tensor>
 {
       {"images", tensor }
 };
 worker.Execute(tensor);
 using TensorFloat output = worker.PeekOutput("output0") as TensorFloat;
 
  output.MakeReadable();
 
var span = output.ToReadOnlySpan();

Unity 2022.3.16f1c1
com.unity.sentis 1.2.0 exp.2

**Comment by marwie** [comment]
Please report the issue to Unity directly - we are just mirroring the packages published by Unity
Thank you
